---
title: "Research Theme Interest: Human Centered Systems Design"
author: "Parsa Khay"
date: "2024-11-06"
categories: [research, ideas]
---

*Background:*
- SSPs are the very initial naratives of the future scenarios. 
- IAMs will describe how is the possible image of the human-earth system based on each scenario 
- IAMs are including technology improvement but not the transformative techs. 
- Human-Robot colaboration is transforming how we consume, how we produce. 
- What if there is no such traditional crop consumption system after 2040s?


*So:*
- Beside the technologists who are developing the tech, there should be systems engineers and analysts who describe the plausible images. 
- There should be more developed naratives responsive to techonology transformations
*Ideas:*
- Develop lifecycle assessments: measuring the functional units of new technologies.
- Compare the dynamics of emerging products: contrasting them with conventional systems.
- Involve integrated assessment modeling: analyse the compound effect of emerging comodities.  

*Challenges:*
- Huge uncertainty 
- No supply-demand curve available


## <span style="color:red;">Can't we see the change? Let's see it together!</span>
Doesn't these technology change how we produce and consume things? Let's put our computational sustainability lenses!\
Economy is impacted by climate change, and the economy is impacted by the transformations we lead in adaption to climate change.

<div style="text-align: center;">
  <iframe src="https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:6976362101502058496" height="400" width="50%" frameborder="0" allowfullscreen="" title="Embedded post"></iframe>
</div>




:::{.columns}
::: {.column width="50%" height="600px"}
# Artificial Taste!
<iframe src="https://tech.notco.com/case-studies" style="border:3px #000000 dashed;" name="NotCo" scrolling="yes" frameborder="1" marginheight="0px" marginwidth="0px" height="275" width="95%" allowfullscreen></iframe>


<iframe width="95%" height="250" src="https://www.youtube.com/embed/jACqrk2ID_w" title="Welcome to NotCo. We are Not Another Company." frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
:::

::: {.column width="50%" height="600px" display="flex" align-items="center"}

# Artificial Smell!

<iframe height="600px" width="80%" src="https://www.youtube.com/embed/bVzn2fqeBy0" title="Scent Teleportation" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
:::
:::



- Developing the idea of the new paradigm: 
*Human Embeded Design*



- Science based, connecting 
that is evolving all the traditional consumption pattern: 



**Theme: Integrated Assessment Modeling:**

- Problem:
  - Emerging solutions to meet sustainability goals are not even imagined in current integrated assessment models. 

- Current conventional models forecast to 2100, keeping all system parameters as usual. 

- Possible research decisions: 

  1- Decision: We run model by 2030 and then introduce new hypothetic techonlogies.
  2- Design a probabilistic model for emerging technologies
  3- The impact of synthetic food / taste on the economy -> Achieving sustinability goals



**Theme(Looks like a fiction, but I will keep it in science): Develop an idea, Develop a Product: a Human Centered Systems Design**

- To be developed
